### ISSUE TITLE
User Auth MVP v1

### ISSUE THREAD

**Issue by ccoombsesmail** [ccoombsesmail/Fidget#2]
#  User Auth

- [x] Displays modal for sign in and log in
- [x] Creates users and logs in properly
- [x] Sign out/in buttons in drop down list
- [x] Displays error messages
- [x] Clears error messages when appropriate
- [x] Has demo user
- [x] Has adequate styling.

Note: Realized still need to handle some errors for dob fields

**Comment by samwalker191** [comment]
- [ ] handle some errors for dob fields :D. i put in a valid dob and got an error with no message 
- [ ] the error box should be the same size as the inputs. It currently sticks a little bit over the left of them.
- [ ] inputs should have padding for the text
- [ ] buttons should have a cursor pointer property when hovered. Disabled buttons should have one too. 
- [ ] I would put a little more space between the session buttons in the header 
- [ ] the session forms feel a little vertically cramped. Id suggest making them taller so that there is more space between everything.

**Comment by ccoombsesmail** [comment]
Ok I think these things should be fixed. Let me know if I missed something. 
Thanks!
